languageCode:           "ru"
title:                  "project X"
# baseURL:                "http://localhost:1313"
# baseURL:                "https://flowbite-admin-dashboard.vercel.app/"
baseUrl:                "http://projectx:1313"
enableInlineShortcodes: true
canonifyURLs: true

params:
  homepage: "http://projectx:1313"
  authors: Themesberg
  social_image_path: images/og-image.png

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
    style:              colorful
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "RSS"]

publishDir:             "_gh_pages"
